import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import Link from "next/link";
// import { Roboto } from "next/font/google";
// import Navbar from "@/components/navbar/Navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// const roboto = Roboto({
//   weight: ["300", "400"],
//   style: ["italic", "normal"],
//   subsets: ["latin"]
// })

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode;}>): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <header>
          <NavBar />
        </header> */}
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
